### ISSUE TITLE
 runtime error: index out of range [48] with length 48

### ISSUE THREAD

**Issue by stamhaney** [dryark/ujsonin#1]
When I am trying to run the registration command: ./main register  while setting up the ios_remote_provider, and press enter on the input field, I am getting the following error:

$ ./main register
Enter registration password:
Using default registration password of doreg
panic: runtime error: index out of range [48] with length 48

goroutine 1 [running]:
github.com/nanoscopic/ujsonin/mod.Parse(0xc000190000, 0x30, 0x600, 0xc000190000, 0x30, 0x600, 0x0)
/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/ujsonin@v1.13.0/mod/ujsonin.go:369 +0x1f83
main.doregister(0xc000068420, 0x0, 0x0)
/Users/utsmacmini/Desktop/controlfloor/ios_remote_provider/controlfloor.go:419 +0x565
main.runRegister(0xc000072230)
/Users/utsmacmini/Desktop/controlfloor/ios_remote_provider/main.go:46 +0x39
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc00015de50)
/users/utsmacmini/go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x240
main.main()

Can you please help

**Comment by nanoscopic** [comment]
This error is referring to this line: https://github.com/dryark/ujsonin/blob/be5728ed145ec32eacaa24faaa22ac8c7608e050/mod/ujsonin.go#L369

The parser was expecting to receive a colon but the file ended and this error results.

The json was likely malformed.

The json being parsed would need to be provided to explain what exactly went wrong and where the misformatting was.
